# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-11 16:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderChatMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'order_chat_message',
            },
        ),
        migrations.RemoveField(
            model_name='order',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='orderchat',
            name='is_read',
        ),
        migrations.RemoveField(
            model_name='orderchat',
            name='message',
        ),
        migrations.RemoveField(
            model_name='orderchat',
            name='recipient',
        ),
        migrations.RemoveField(
            model_name='orderchat',
            name='sender',
        ),
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='order_customer', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderchat',
            name='contractor_last_read_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='orderchat',
            name='messages_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orderchat',
            name='recipient_new_messages_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orderchat',
            name='sender_last_read_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='orderchat',
            name='sender_new_messages_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='orderattachment',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='api.Order'),
        ),
        migrations.AlterField(
            model_name='orderchatattachment',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_attachments', to='api.OrderChatMessage'),
        ),
        migrations.AddField(
            model_name='orderchatmessage',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='api.OrderChat'),
        ),
        migrations.AddField(
            model_name='orderchatmessage',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_chat_sender', to=settings.AUTH_USER_MODEL),
        ),
    ]
