# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-11 16:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20161211_1634'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderchat',
            old_name='recipient_new_messages_count',
            new_name='contractor_new_messages_count',
        ),
        migrations.RenameField(
            model_name='orderchat',
            old_name='sender_last_read_at',
            new_name='customer_last_read_at',
        ),
        migrations.RenameField(
            model_name='orderchat',
            old_name='sender_new_messages_count',
            new_name='customer_new_messages_count',
        ),
    ]
