# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-11 16:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20161211_1635'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderattachment',
            old_name='creator',
            new_name='customer',
        ),
    ]
