# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-30 09:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_orderchat_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordercategory',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='api.OrderCategory'),
        ),
    ]
