# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-30 09:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_ordercategory_parent_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordercategory',
            old_name='parent_id',
            new_name='parent',
        ),
    ]
