# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-18 16:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20170111_1044'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailLog',
        ),
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
