# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 02:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_orderapplication_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderapplication',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='orderapplication',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_application', to='api.Order'),
        ),
        migrations.AlterField(
            model_name='orderapplication',
            name='status',
            field=models.IntegerField(choices=[(0, 'NEW'), (1, 'ACCEPTED'), (2, 'DECLINED'), (3, 'WITHDRAWN')], default=0),
        ),
    ]
